#!/bin/bash

# Quick Start Guide for Z-Check Graph & WhatsApp Alerts
# Run this to see status and get next steps

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║            Z-Check: Graph & WhatsApp Setup Status                ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

# Check all services
echo "📋 Service Status:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

docker ps --format "table {{.Names}}\t{{.Status}}" | grep zcheck

echo ""
echo "✅ Your Phone Number: +918765290618"
echo ""

echo "📊 Dashboard Access:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 http://localhost:3000"
echo ""
echo "   What you'll see:"
echo "   ✅ Graph with 4 Organizations, 4 Services, 4 Endpoints"
echo "   ✅ Green health badge at top (0% UP = all endpoints DOWN)"
echo "   ✅ Live Feed showing real-time status changes"
echo "   ✅ Download JSON/CSV export buttons"
echo ""

echo "🔧 Test Alert Now:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command:"
echo ""
echo "  curl -X POST http://localhost:8080/api/test-check \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"id\": \"ep-stripe-status\"}'"
echo ""
echo "Then:"
echo "  1. Watch for RED TOAST notification (top-right)"
echo "  2. Check LIVE FEED (bottom) for status change"
echo "  3. Verify graph highlights red path"
echo ""

echo "📱 Setup WhatsApp Alerts (Next Step):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⭐ RECOMMENDED: Twilio Free Trial"
echo ""
echo "1. Sign up: https://www.twilio.com/console"
echo "2. Get: Account SID + Auth Token"
echo "3. Edit: .env file"
echo ""
echo "   WHATSAPP_API_URL=https://api.twilio.com/2010-04-01/Accounts/{ACCOUNT_SID}/Messages.json"
echo "   WHATSAPP_API_TOKEN={YOUR_AUTH_TOKEN}"
echo "   ALERT_WHATSAPP_TO=+918765290618"
echo ""
echo "4. Restart:"
echo ""
echo "   docker compose up --build -d"
echo ""
echo "5. Test:"
echo ""
echo "   curl -X POST http://localhost:8080/api/test-check \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"id\": \"ep-stripe-status\"}'"
echo ""
echo "   → Check your phone for WhatsApp message!"
echo ""

echo "📖 Full Documentation:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "See: GRAPH_AND_WHATSAPP_SETUP.md"
echo ""

echo "✨ Current Status:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Graph: WORKING"
echo "✅ Alerts (Dashboard): WORKING"
echo "✅ Phone: CONFIGURED (+918765290618)"
echo "⏳ WhatsApp: AWAITING API TOKEN"
echo ""

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║  Open http://localhost:3000 in browser to see your graph!        ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
